### ISSUE TITLE
Int32 is not enough for InReplyToUserId

### ISSUE THREAD

**Issue by kanertuncel** [danielcrenna/tweetsharp#170]
I had an error while searching a tag on twitter, It says JSON integer 3108362464 is too large or small for an Int32. Path 'statuses[46].in_reply_to_user_id', line 1, position 145311.

I think it needs an update on TwitterStatus.cs on line 31 
public virtual int? InReplyToUserId { get; set; } 
=> 
public virtual long? InReplyToUserId { get; set; }

**Comment by Yortw** [comment]
Are you using the NuGet package? It sounds like you are. The NuGet package is out of date and does not contain the latest fixes. I think you'll find if you check the actual source this issue has already been fixed. This project has been abandoned by the author and the Nuget package is not being updated. You either need to download the source and compile it yourself, or use one of the alternate forks. There are several alternate forks, at least two of which are available via NuGet. My own one is called "TweetMoaSharp".

**Comment by kanertuncel** [comment]
Thank you!

**Comment by Yortw** [comment]
No problem.
