### ISSUE TITLE
DeleteTweet does nothing

### ISSUE THREAD

**Issue by wallnutkraken** [danielcrenna/tweetsharp#181]
The DeleteTweet method in the TwitterService class does not delete the tweet that it is told to.
To recreate:
Start a tweetsharp project, create a TwitterService object, authenticate it with a user's Twitter account, get the ID of a tweet by the user, try using DeleteTweet() with the options to delete the tweet with that ID.

Result: nothing happens

Expected result: tweet is deleted

**Comment by Yortw** [comment]
Hi,

I haven't had time to retest to confirm yet, but I believe DeleteTweet works correctly in the TweetMoaSharp fork. TweetSharp is no longer being maintained, so you either need to fix the code yourself, switch to one of the active forks, or change to another library altogether.

**Comment by wallnutkraken** [comment]
Yeah that's what I moved my twitter project too. Thanks!
