### ISSUE TITLE
Unable to translate Unicode character

### ISSUE THREAD

**Issue by mslade1969** [danielcrenna/tweetsharp#191]
I'm getting an error when retrieving a list of tweets on a users timeline using ListTweetsOnUserTimeline.

The error is:- 

Unable to translate Unicode character \uD83C at index 294 to specified code page.

I'm guessing that the tweet contains an emoji.

Is there any way of either:

a) translating these charaters
or
b) blocking these from causing the error

Thanks

M

**Comment by Yortw** [comment]
Any chance of providing the tweet or user id? That will help others test/look into the problem and possible solutions.

You're likely right and it is a Unicode character not supported by the encoding in use, but potentially it could be Twitter returning a compressed response to a platform that doesn't support decompression. What platform are you using? (There was an issue like that which caused an error on certain WinRT ports a while back).

Assuming it is a Unicode issue you might be able to work around it by changing the encoding used on the json serialiser, but it's just a stab in the dark.I assume its using utf8 and probably utf16 would work, but I'm not an expert on this so I may be wrong.

**Comment by mslade1969** [comment]
I'm sorry, but I think the tweet got removed so I can't supply that. I think it was a problem with an emoji or something strange like that. 

We are using plain old .NET 4.5 no WinRT here.

I did a test with TweetMoaSharp and that didn't experience the same problem so I guess we are resolved.

Thanks

M
